### ISSUE TITLE
Collapse-funktion för filtrering

### ISSUE THREAD

**Issue by Reellron** [flowertwig-org/polisensvolontarer#38]
Filtreringen tar upp väldigt mycket utrymme på skärmen, med "Dölj"-knapp för <form id="available-assignments-filter-container"> så kunde man lösa detta.
Ändringen vore till för användarvänlighet för slutanvändaren.

![idag](https://user-images.githubusercontent.com/43376247/46894837-25c60f80-ce76-11e8-8b54-8479bf12c3fd.jpg)
![forslag filter dolt](https://user-images.githubusercontent.com/43376247/46894839-25c60f80-ce76-11e8-8444-958b4bb0a7e6.jpg)
![forslag filter visas](https://user-images.githubusercontent.com/43376247/46894840-25c60f80-ce76-11e8-9830-b13114f79e33.jpg)

**Comment by flowertwig-org** [comment]
Har aldrig själva haft så många filtreringar så har inte märkt detta :) 
Förslag är att istället vända på det.
Alltså att bara visa ATT aktiv filtrering finns men att man måste klicka på "Visa aktiv filtrering".
Kanske även göra så att vi bara döljer valen om man har mer än tex 5 filtreringar.
Vad tror du om detta?

**Comment by flowertwig-org** [comment]
<img width="857" alt="screenshot 2018-12-16 at 09 46 55" src="https://user-images.githubusercontent.com/4742476/50051722-91975380-0117-11e9-81f0-343da199a771.png">

**Comment by flowertwig-org** [comment]
Vi visar alla filtreringar så länge man bara har 5 eller färre, annars grupperar vi dem enligt bilden ovan
